### PR TITLE
Solve permissions android m

### PR DESCRIPTION
**Pull request by jmanuelrosa**

### CODE REVIEW

**Comment by cicloon** [comment]
It's hard to know what changed when all the 4 space tabs have been replaced by 2 space tabs :(

**Comment by ciscou** [comment]
I wonder why the whitespace trick doesn't work here :(

https://github.com/blog/967-github-secrets

**Comment by jmanuelrosa** [comment]
Bah, the only thing is @lurecas  and I modify that mix the management of permissions the previous plugin, if it worked with Android M

**Comment by cicloon** [comment]
🙈

**Pull request merged**
